# Generated by Django 4.2.5 on 2024-03-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoilQMS', '0002_crops_usercrops_soilreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoilReport',
            new_name='UserCropsHistory',
        ),
    ]
