# Generated by Django 4.2.5 on 2024-03-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoilQMS', '0003_rename_soilreport_usercropshistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
        migrations.RenameModel(
            old_name='UserCrops',
            new_name='UserCrop',
        ),
        migrations.RenameModel(
            old_name='UserCropsHistory',
            new_name='UserCropHistory',
        ),
        migrations.AlterModelOptions(
            name='usercrophistory',
            options={'verbose_name_plural': 'UserCropHistory'},
        ),
    ]
