# Generated by Django 4.2.5 on 2024-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoilQMS', '0004_rename_crops_crop_rename_usercrops_usercrop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='moisture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='nutrients',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='ph_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usercrop',
            name='moisture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usercrop',
            name='nutrients',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usercrop',
            name='ph_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usercrop',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
