# Generated by Django 4.2.5 on 2024-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoilQMS', '0005_alter_crop_moisture_alter_crop_nutrients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrophistory',
            name='moisture',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercrophistory',
            name='nutrients',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercrophistory',
            name='ph_value',
            field=models.FloatField(default=222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercrophistory',
            name='temperature',
            field=models.FloatField(default=221),
            preserve_default=False,
        ),
    ]
